### ISSUE TITLE
`SchemaNameBase::pivotItem()` method should not be `static`

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/schema_metatag#2]
My IDE is complaining about the `SchemaNameBase::pivotItem()` method because there is a line that uses the special keyword `$this` in it:

```
$array = $this->schemaMetatagManager()->pivot($array);
```

But this method is defined as `public static function pivotItem($array)`. A static method cannot use the `$this` keyword because that requires an instance of the class to exist, while a static method is one that can be called without creating an instance of the class.

Based on the way this method is called, I don't see any reason why this method needs to be static. Note that a method with the same name in `SchemaMetatagManager` can remain static.

**Comment by argiepiano** [comment]
@quicksketch, thanks for catching this and for providing a PR. Can you please edit the doc block to include documentation for the method? `{@inheritdoc}` is not appropriate since this method is not extending another method.
