### ISSUE TITLE
PHP 8.3 notices

### ISSUE THREAD

**Issue by dgbruns** [backdrop-contrib/schema_metatag#6]
I'm testing Backdrop with PHP 8.3 and seeing the following notices:

```
Deprecated function: Creation of dynamic property SchemaOrganizationType::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaNameBase::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaUrlBase::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaImageBase::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Use of "static" in callables is deprecated in SchemaNameBase->getElement() (line 123 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaPersonOrgBase::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaArticleType::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Creation of dynamic property SchemaDateBase::$options is deprecated in SchemaNameBase->getElement() (line 105 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaNameBase.php).
Deprecated function: Use of "static" in callables is deprecated in SchemaTypeBase::types() (line 55 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaTypeBase.php).
```

Let me know if I can provide more info.

**Comment by argiepiano** [comment]
Thanks for reporting. This is an easy fix. I'll get to this tonight.

**Comment by argiepiano** [comment]
@dgbruns, can you please patch the module with the PR provided here and check if this solves the issue? If so, I'll merge and will do a new release.

**Comment by dgbruns** [comment]
@argiepiano , one more in there still from the original list above:

`Deprecated function: Use of "static" in callables is deprecated in SchemaTypeBase::types() (line 55 of /var/www/html/web/modules/contrib/schema_metatag/src/SchemaTypeBase.php).
`

Note I am only using Organization and Article types on this site so I'm not clear if I am flushing out all potential errors. If you have any suggestions please let me know.

**Comment by argiepiano** [comment]
Thanks! I took care of that one now. Can you test?

**Comment by dgbruns** [comment]
I tested again with the new patch and I'm not seeing any errors. I also enabled a two new schemas, did some minimal config and did not see any errors. This is a pretty complex module and I'm not sure how to test php 8.3 in a better way, but for now, no errors!

**Comment by argiepiano** [comment]
Great! Yes, it's a complex module, but all classes provided by the module extend `SchemaTypeBase`. So, by modifying that base class, we've solved the issue for all children. I'll merge and do a new release. Thanks for reporting and testing!
